### ISSUE TITLE
The latest build fails…

### ISSUE THREAD

**Issue by Foddy** [galexrt/docker-healthchecks#23]
The latest build is failing to start. It used to work a week ago?

```
Added "PING_ENDPOINT" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "ALLOWED_HOSTS" (type "plain") to local_settings.py
16.12.2019 15:14:31 Added "EMAIL_HOST" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "SECRET_KEY" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "REGISTRATION_OPEN" (type "plain") to local_settings.py
16.12.2019 15:14:31 Added "MASTER_BADGE_LABEL" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "EMAIL_PORT" (type "plain") to local_settings.py
16.12.2019 15:14:31 Added "SITE_NAME" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "USE_PAYMENTS" (type "plain") to local_settings.py
16.12.2019 15:14:31 Added "SITE_ROOT" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "EMAIL_HOST_PASSWORD" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "EMAIL_HOST_USER" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "DEBUG" (type "plain") to local_settings.py
16.12.2019 15:14:31 Added "HOST" (type "string") to local_settings.py
16.12.2019 15:14:31 Added "EMAIL_USE_TLS" (type "plain") to local_settings.py
16.12.2019 15:14:31 Added "DEFAULT_FROM_EMAIL" (type "string") to local_settings.py
16.12.2019 15:14:31 Traceback (most recent call last):
16.12.2019 15:14:31 File "/healthchecks/manage.py", line 10, in <module>
16.12.2019 15:14:31 execute_from_command_line(sys.argv)
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
16.12.2019 15:14:31 utility.execute()
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 325, in execute
16.12.2019 15:14:31 settings.INSTALLED_APPS
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 79, in __getattr__
16.12.2019 15:14:31 self._setup(name)
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 66, in _setup
16.12.2019 15:14:31 self._wrapped = Settings(settings_module)
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 157, in __init__
16.12.2019 15:14:31 mod = importlib.import_module(self.SETTINGS_MODULE)
16.12.2019 15:14:31 File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
16.12.2019 15:14:31 return _bootstrap._gcd_import(name[level:], package, level)
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 986, in _gcd_import
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 969, in _find_and_load
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
16.12.2019 15:14:31 File "<frozen importlib._bootstrap_external>", line 673, in exec_module
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
16.12.2019 15:14:31 File "/healthchecks/hc/settings.py", line 38, in <module>
16.12.2019 15:14:31 for line in open(os.path.join(BASE_DIR, "CHANGELOG.md")).readlines():
16.12.2019 15:14:31 File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
16.12.2019 15:14:31 return codecs.ascii_decode(input, self.errors)[0]
16.12.2019 15:14:31 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1813: ordinal not in range(128)
16.12.2019 15:14:31 Correcting config file permissions ...
16.12.2019 15:14:31 Migrating database ...
16.12.2019 15:14:31 Traceback (most recent call last):
16.12.2019 15:14:31 File "/healthchecks/manage.py", line 10, in <module>
16.12.2019 15:14:31 execute_from_command_line(sys.argv)
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
16.12.2019 15:14:31 utility.execute()
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 325, in execute
16.12.2019 15:14:31 settings.INSTALLED_APPS
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 79, in __getattr__
16.12.2019 15:14:31 self._setup(name)
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 66, in _setup
16.12.2019 15:14:31 self._wrapped = Settings(settings_module)
16.12.2019 15:14:31 File "/home/healthchecks/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 157, in __init__
16.12.2019 15:14:31 mod = importlib.import_module(self.SETTINGS_MODULE)
16.12.2019 15:14:31 File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
16.12.2019 15:14:31 return _bootstrap._gcd_import(name[level:], package, level)
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 986, in _gcd_import
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 969, in _find_and_load
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
16.12.2019 15:14:31 File "<frozen importlib._bootstrap_external>", line 673, in exec_module
16.12.2019 15:14:31 File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
16.12.2019 15:14:31 File "/healthchecks/hc/settings.py", line 38, in <module>
16.12.2019 15:14:31 for line in open(os.path.join(BASE_DIR, "CHANGELOG.md")).readlines():
16.12.2019 15:14:31 File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
16.12.2019 15:14:31 return codecs.ascii_decode(input, self.errors)[0]
16.12.2019 15:14:31 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1813: ordinal not in range(128)
16.12.2019 15:14:32 2019-12-16 14:14:32,168 INFO supervisord started with pid 1
16.12.2019 15:14:33 2019-12-16 14:14:33,172 INFO spawned: 'nginx' with pid 17
16.12.2019 15:14:33 2019-12-16 14:14:33,175 INFO spawned: 'gunicorn' with pid 18
16.12.2019 15:14:33 2019-12-16 14:14:33,177 INFO spawned: 'sendalerts' with pid 19
16.12.2019 15:14:33 2019-12-16 14:14:33,288 INFO exited: sendalerts (exit status 1; not expected)
16.12.2019 15:14:33 2019-12-16 14:14:33,668 INFO exited: gunicorn (exit status 3; not expected)
16.12.2019 15:14:34 2019-12-16 14:14:34,668 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
16.12.2019 15:14:34 2019-12-16 14:14:34,670 INFO spawned: 'gunicorn' with pid 25
16.12.2019 15:14:34 2019-12-16 14:14:34,673 INFO spawned: 'sendalerts' with pid 26
16.12.2019 15:14:34 2019-12-16 14:14:34,766 INFO exited: sendalerts (exit status 1; not expected)
16.12.2019 15:14:35 2019-12-16 14:14:35,150 INFO exited: gunicorn (exit status 3; not expected)
16.12.2019 15:14:37 2019-12-16 14:14:37,154 INFO spawned: 'gunicorn' with pid 31
16.12.2019 15:14:37 2019-12-16 14:14:37,157 INFO spawned: 'sendalerts' with pid 32
16.12.2019 15:14:37 2019-12-16 14:14:37,262 INFO exited: sendalerts (exit status 1; not expected)
16.12.2019 15:14:37 2019-12-16 14:14:37,591 INFO exited: gunicorn (exit status 3; not expected)
16.12.2019 15:14:40 2019-12-16 14:14:40,365 INFO spawned: 'sendalerts' with pid 37
16.12.2019 15:14:40 2019-12-16 14:14:40,475 INFO exited: sendalerts (exit status 1; not expected)
16.12.2019 15:14:41 2019-12-16 14:14:41,478 INFO spawned: 'gunicorn' with pid 38
16.12.2019 15:14:41 2019-12-16 14:14:41,479 INFO gave up: sendalerts entered FATAL state, too many start retries too quickly
16.12.2019 15:14:41 2019-12-16 14:14:41,975 INFO exited: gunicorn (exit status 3; not expected)
16.12.2019 15:14:42 2019-12-16 14:14:42,977 INFO gave up: gunicorn entered FATAL state, too many start retries too quickly
```

**Comment by galexrt** [comment]
I have pushed a fix in b84b85d.
New images should be built in a few minutes from now.

The issue seems to be caused by the `CHANGELOG.md` file which for some reason has an invalid encoded character in it and causes the compress and other `manage.py` commands to fail.

**Comment by Foddy** [comment]
Thank you for your fast reply. Unfortunately the build process is failing now :S
https://quay.io/repository/galexrt/healthchecks

**Comment by galexrt** [comment]
@Foddy Damn, yeah it seems that the current `master` of healthchecks/healthchecks has switched / updated to Django 3. Django 3 doesn't seem to able to be able installed.
The `master` image now installs `v1.11.0`, see 90150a56839a41b48788fb4ef8763cd463089976.

**Comment by BobCashStory** [comment]
Any update on that?

**Comment by galexrt** [comment]
@BobCashStory What do you mean? The image uses the `v1.11.0` tag and has been built fine as can be seen on Quay.io (see above link).

"in this version" means, that the "now" latest build using `v1.11.0` has that problem?
Have you made sure it is not a browser caching issue?

**Comment by BobCashStory** [comment]
in the v1.11.0 on the url `[host]/admin`, i get 404 for all css file from `[host]/static/admin/css/base.css` net::ERR_ABORTED 404
if i check the repo files should be get into `[host]/static/css/base.css` .

**Comment by galexrt** [comment]
@BobCashStory That is probably a configuration issue in some ways.
This Healthchecks project issue seems to be related https://github.com/healthchecks/healthchecks/issues/150 though there isn't a clear answer on that issue.

**Comment by BobCashStory** [comment]
Okay thanks, and about using the lasted version do you have any update to be on `v1.12.0`

**Comment by galexrt** [comment]
@BobCashStory please create a new issue for that.
v1.12.0 has been released a few days ago, hoping they have updated their instructions it shouldn't be long.
