### ISSUE TITLE
Postgres database not being selected

### ISSUE THREAD

**Issue by jeliasson** [galexrt/docker-healthchecks#26]
Hi,

According to docs, `DB_TYPE` should be set to `postgres`. However, in the source `hc/settings.py` it looks like `DB` should be set as `postgres` - hence `HC_DB` rather than `HC_DB_TYPE`. The intresting part tho, non of them works and output of `hc/local_settings.py` will show a connection to SqlLite3.

**Envs**
```env
HC_DB: "postgres"
HC_DB_TYPE: "postgres"
HC_DB_HOST: "postgres.example.com"
HC_DB_PORT: "5432"
HC_DB_NAME: "default"
HC_DB_USER: "postgres"
HC_DB_PASSWORD: "postgres"
```
**/healthchecks/hc/local_settings.py**
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/data/hc.sqlite',
    }
}
EMAIL_HOST_PASSWORD = "SG.0FVIewlzQ72XU..."
DB_NAME = "default"
SITE_ROOT = "https://hc.example.com"
DEBUG = False
DB = "postgres"
DB_HOST = "postgres.example.com"
SITE_NAME = "HC"
HOST = "0.0.0.0"
SECRET_KEY = "Aab..."
DISCORD_CLIENT_SECRET = "Xhyt_i33Rd8..."
ALLOWED_HOSTS = ["hc.example.com", "healthchecks.example.com"]
PING_ENDPOINT = "https://hc.example.com/ping/"
MASTER_BADGE_LABEL = "HealthChecks"
EMAIL_HOST_USER = "apikey"
REGISTRATION_OPEN = True
DB_TYPE = "postgres"
DB_USER = "postgres"
USE_PAYMENTS = False
DB_PORT = 5432
DB_PASSWORD = "postgres"
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "hc@example.com"
PING_EMAIL_DOMAIN = "hc.example.com"
EMAIL_HOST = "smtp.example.com"
EMAIL_PORT = 587
DISCORD_CLIENT_ID = 1234567
```

Any thoughts?
Thanks!

**Comment by galexrt** [comment]
You can just use the env vars from the healthchecks project settings.py now.
I have removed all the entrypoint code to do any custom configuration, so the `settings.py` comes into full effect.

So does removing the `HC` in front of your env vars work with the latest image? (Quay.io image is already uptodate, Docker Hub still needs a few more minutes to auto build).

**Comment by jeliasson** [comment]
> You can just use the env vars from the healthchecks project settings.py now.

Neat!

> So does removing the `HC` in front of your env vars work with the latest image? (Quay.io image is already uptodate, Docker Hub still needs a few more minutes to auto build).

Running some tests now with `galexrt/healthchecks:latest`. Getting back to you soon.

**Comment by jeliasson** [comment]
There is something that is acting up. Worth mentioning is that I'm deploying this to Kubernetes, but besides some minor permissions issues it should not be this hard.

Currently I'm struggling with the `/healthchecks` being empty at first run, which requires me to clone `healthchecks/healthchecks` manually. After that I get the error message below, without any `healthchecks/hc/local_settings.py` being generated.

```bash
/entrypoint.sh: line 13: databaseConfiguration: command not found
/entrypoint.sh: line 14: settingsConfiguration: command not found
Compressing... done
Compressed 18 block(s) from 98 template(s) for 0 context(s).
You have requested to collect static files at the destination
location as specified in your settings:
    /healthchecks/static-collected
This will overwrite existing files!
Are you sure you want to do this?
Traceback (most recent call last):
  File "/healthchecks/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 104, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 130, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files
    yield from get_files(storage, ignore_patterns, dir)
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files
    yield from get_files(storage, ignore_patterns, dir)
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files
    yield from get_files(storage, ignore_patterns, dir)
  [Previous line repeated 37 more times]
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
    directories, files = storage.listdir(location)
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/files/storage.py", line 317, in listdir
    if entry.is_dir():
OSError: [Errno 40] Too many levels of symbolic links: '/healthchecks/static/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE'
ln: failed to create symbolic link '/healthchecks/static/CACHE/CACHE': File exists
Type 'yes' to continue, or 'no' to cancel: Correcting config file permissions ...
Migrating database ...
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:
  No migrations to apply.
2020-02-22 23:19:29,660 INFO supervisord started with pid 1
2020-02-22 23:19:30,663 INFO spawned: 'nginx' with pid 19
2020-02-22 23:19:30,665 INFO spawned: 'gunicorn' with pid 20
2020-02-22 23:19:30,666 INFO spawned: 'sendalerts' with pid 21
2020-02-22 23:19:31,734 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-22 23:19:31,734 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-22 23:19:31,734 INFO success: sendalerts entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Right now I'm on the verge of manually copying in `local_settings.py` from a `ConfigMap` as a work-around. If you know what's going on, please let me know.

**Comment by galexrt** [comment]
You shouldn't need to copy in the local_settings.py that is just a "warning" which is completely okay in this case.

I have pushed some improvements to `master` and tagged it as `v1.13.0-0`. The images should be available in like 30 minutes or so.

***

Are you mounting the `/healthchecks` direcotry somewhere? Using the latest Docker image there is no need to do any manual steps so you seem to mount / do something which breaks the image.

**Comment by jeliasson** [comment]
> I have pushed some improvements to `master` and tagged it as `v1.13.0-0`. The images should be available in like 30 minutes or so.

Seems to have been built, but Docker Hub is missing the tag. Can you please tag it manually?
 
> Are you mounting the `/healthchecks` direcotry somewhere? Using the latest Docker image there is no need to do any manual steps so you seem to mount / do something which breaks the image.

Yes. Is there no need to mount? I got confused by the [volume mapping](https://github.com/galexrt/docker-healthchecks/commit/3e76392a04163936c236f69dce6893f6e3c4f7cc#diff-04c6e90faac2675aa89e2176d2eec7d8R149).

**Comment by galexrt** [comment]
@jeliasson Yeah those mounts shouldn't be there. I have updated the README to fix the unnecessary mounts and added some more info regarding configuration.
