### ISSUE TITLE
Issue with Fonts/Static Items

### ISSUE THREAD

**Issue by jimmybrancaccio** [galexrt/docker-healthchecks#27]
This may be related to bf85f25 but I am not positive. I'm getting 404 errors on font files:

<img width="1680" alt="Screen Shot 2020-02-25 at 4 03 28 PM" src="https://user-images.githubusercontent.com/405585/75291719-6236a900-57e8-11ea-9c0d-f602dedbefee.png">

I see this from the Nginx logs:

```
2020/02/25 16:01:53 [error] 18#18: *3 open() "/healthchecks/static-collected//fonts/icomoon.woff" failed (2: No such file or directory), client: 172.18.0.1, server: _, request: "GET /static/fonts/icomoon.woff?jvwv9j HTTP/1.1", host: "hc.linuxbox.ninja", referrer: "https://hc.linuxbox.ninja/projects/xxxxxxxx-xxxx-479d-xxxx-xxxxxxxx/checks/"
172.18.0.1 - - [25/Feb/2020:16:01:53 -0600] "GET /static/fonts/icomoon.woff?jvwv9j HTTP/1.1" 404 169 "https://hc.linuxbox.ninja/projects/xxxxxxxx-xxxx-479d-xxxx-xxxxxxxx/checks/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15"
2020/02/25 16:01:54 [error] 18#18: *3 open() "/healthchecks/static-collected//fonts/icomoon.svg" failed (2: No such file or directory), client: 172.18.0.1, server: _, request: "GET /static/fonts/icomoon.svg?jvwv9j HTTP/1.1", host: "hc.linuxbox.ninja", referrer: "https://hc.linuxbox.ninja/projects/xxxxxxxx-xxxx-479d-xxxx-xxxxxxxx/checks/"
```

and in the other log I see:

```
Compressing... Invalid template /healthchecks/templates/integrations/add_pd.html: 'staticfiles' is not a registered tag library. Must be one of:,
admin_list,
admin_modify,
admin_urls,
cache,
compress,,
s,
humanize,
i18n,
l10n,
log,
static,
tz,
done,
Compressed 18 block(s) from 96 template(s) for 0 context(s).,
,
You have requested to collect static files at the destination,
location as specified in your settings:,
,
    /healthchecks/static-collected,
,
This will overwrite existing files!,
Are you sure you want to do this?,
,
Traceback (most recent call last):,
  File "/healthchecks/manage.py", line 10, in <module>,
    execute_from_command_line(sys.argv),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line,
    utility.execute(),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute,
    self.fetch_command(subcommand).run_from_argv(self.argv),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv,
    self.execute(*args, **cmd_options),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute,
    output = self.handle(*args, **options),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle,
    collected = self.collect(),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 104, in collect,
    for path, storage in finder.list(self.ignore_patterns):,
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 130, in list,
    for path in utils.get_files(storage, ignore_patterns):,
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files,
    yield from get_files(storage, ignore_patterns, dir),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files,
    yield from get_files(storage, ignore_patterns, dir),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 39, in get_files,
    yield from get_files(storage, ignore_patterns, dir),
  [Previous line repeated 37 more times],
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files,
    directories, files = storage.listdir(location),
  File "/home/healthchecks/.local/lib/python3.7/site-packages/django/core/files/storage.py", line 317, in listdir,
    if entry.is_dir():,
OSError: [Errno 40] Too many levels of symbolic links: '/healthchecks/static/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE/CACHE',
Type 'yes' to continue, or 'no' to cancel: Correcting config file permissions ...,
Migrating database ...,
System check identified some issues:,
,,
:,
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default',
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/3.0/ref/databases/#mysql-sql-mode,
Operations to perform:,
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions,
Running migrations:,
  No migrations to apply.,
  Your models have changes that are not yet reflected in a migration, and so won't be applied.,
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.,
2020-02-25 16:01:07,705 INFO supervisord started with pid 1,
2020-02-25 16:01:08,707 INFO spawned: 'nginx' with pid 15,
2020-02-25 16:01:08,710 INFO spawned: 'gunicorn' with pid 16,
2020-02-25 16:01:08,712 INFO spawned: 'sendalerts' with pid 17,
2020-02-25 16:01:09,944 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2020-02-25 16:01:09,944 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2020-02-25 16:01:09,944 INFO success: sendalerts entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
```

Any ideas?

Also I've noticed I believe this breaks the logo image in email. The HTML from the email is:

``` html
<img alt="Logo" src="https://hc.linuxbox.ninja/static/img/logo-full@2x.png" width="200" height="50" style="display: block; font-family: Helvetica, Arial, sans-serif; color: #ffffff; font-size: 16px;" border="0">
```

**Comment by galexrt** [comment]
Post the `docker run` or `docker-compose.yml` you use to run docker-healthchecks.
Which Docker image tag are you running?

Post the whole container logs after a `docker stop`, `docker rm` and docker run` (same goes for docker-compose).

**Comment by jimmybrancaccio** [comment]
Okay, after looking at my `docker-compose.yml` bit and then looking back at the README, it looks like a few things changed. I removed a couple of my volumes, specifically one that binded to `/healthchecks` and `/data` in the container and removed those. Then restarted the container and now it seems to be happier. Fonts and images are loading properly now. I think we can consider this one closed 😄
