### ISSUE TITLE
Fully Qualified Hostname has to be set for E-Mails

### ISSUE THREAD

**Issue by Braintelligence** [galexrt/docker-healthchecks#7]
When trying to send mails I got this:

```
27.12.2017 17:26:55Exception in thread Thread-39:
27.12.2017 17:26:55Traceback (most recent call last):
27.12.2017 17:26:55  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
27.12.2017 17:26:55    self.run()
27.12.2017 17:26:55  File "/healthchecks/hc/lib/emails.py", line 22, in run
27.12.2017 17:26:55    msg.send()
27.12.2017 17:26:55  File "/healthchecks/hc-venv/lib/python3.4/site-packages/django/core/mail/message.py", line 348, in send
27.12.2017 17:26:55    return self.get_connection(fail_silently).send_messages([self])
27.12.2017 17:26:55  File "/healthchecks/hc-venv/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 111, in send_messages
27.12.2017 17:26:55    sent = self._send(message)
27.12.2017 17:26:55  File "/healthchecks/hc-venv/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 127, in _send
27.12.2017 17:26:55    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
27.12.2017 17:26:55  File "/usr/lib/python3.4/smtplib.py", line 793, in sendmail
27.12.2017 17:26:55    raise SMTPRecipientsRefused(senderrs)
27.12.2017 17:26:55smtplib.SMTPRecipientsRefused: {'my@mailaddress.com': (504, b'5.5.2 <5c632f939fd4>: Helo command rejected: need fully-qualified hostname')}
```

After setting the FQDN in the container this didn't happen anymore, I get a HTTP 200 instead. But I still don't get mails it seems. Will look into this.

**Comment by galexrt** [comment]
That is a configuration specific issue to healthchecks, not an issue of the Docker image.

**Comment by Braintelligence** [comment]
How so?
The FQDN is set within the OS. Why is a Django app obliged to do this for you, without root permissions?

**Comment by Braintelligence** [comment]
What I said is correct, though I found out that I can use port 587 for authenticated sending, which doesn't need a FQDN.
So this doesn't necessarily need to be corrected.
